import java.util.*;
import java.io.*;

public class LLm_Training {
    static class Context {
        List<String> tokens;
        
        Context(List<String> tokens) {
            this.tokens = tokens;
        }
        
        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (!(o instanceof Context)) return false;
            Context c = (Context) o;
            return tokens.equals(c.tokens);
        }
        
        @Override
        public int hashCode() {
            return tokens.hashCode();
        }
    }
    
    public static void main(String[] args) throws IOException {
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        PrintWriter pw = new PrintWriter(System.out);
        
        int n = Integer.parseInt(br.readLine().trim());
        
        List<List<String>> texts = new ArrayList<>();
        List<String> llmFlags = new ArrayList<>();
        int maxLen = 0;
        
        for (int i = 0; i < n; i++) {
            int m = Integer.parseInt(br.readLine().trim());
            maxLen = Math.max(maxLen, m);
            
            String[] tokens = br.readLine().trim().split("\\s+");
            List<String> textTokens = new ArrayList<>();
            for (String token : tokens) {
                textTokens.add(token);
            }
            texts.add(textTokens);
            
            String flags = br.readLine().trim();
            llmFlags.add(flags);
        }
        
        // For each context size k
        for (int k = 0; k < maxLen; k++) {
            Map<Context, Map<String, Integer>> contextCounts = new HashMap<>();
            
            // Collect statistics for context size k
            for (int i = 0; i < n; i++) {
                List<String> text = texts.get(i);
                String flags = llmFlags.get(i);
                
                for (int j = 0; j < text.size(); j++) {
                    if (flags.charAt(j) == 'L') {
                        // This token is generated by LLM
                        int start = Math.max(0, j - k);
                        List<String> contextTokens = text.subList(start, j);
                        Context ctx = new Context(contextTokens);
                        
                        String nextToken = text.get(j);
                        
                        contextCounts.putIfAbsent(ctx, new HashMap<>());
                        Map<String, Integer> tokenCounts = contextCounts.get(ctx);
                        tokenCounts.put(nextToken, tokenCounts.getOrDefault(nextToken, 0) + 1);
                    }
                }
            }
            
            // Calculate loss
            double loss = 0.0;
            
            for (int i = 0; i < n; i++) {
                List<String> text = texts.get(i);
                String flags = llmFlags.get(i);
                
                for (int j = 0; j < text.size(); j++) {
                    if (flags.charAt(j) == 'L') {
                        int start = Math.max(0, j - k);
                        List<String> contextTokens = text.subList(start, j);
                        Context ctx = new Context(contextTokens);
                        
                        String nextToken = text.get(j);
                        
                        Map<String, Integer> tokenCounts = contextCounts.get(ctx);
                        int totalCount = 0;
                        for (int count : tokenCounts.values()) {
                            totalCount += count;
                        }
                        
                        int tokenCount = tokenCounts.get(nextToken);
                        double probability = (double) tokenCount / totalCount;
                        
                        // Add -log2(probability) to loss
                        loss += -Math.log(probability) / Math.log(2);
                    }
                }
            }
            
            pw.printf("%.12f\n", loss);
        }
        
        pw.flush();
        pw.close();
    }
}